### ISSUE TITLE
Check documentation for broken links

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/step-dir#1]
Since [intra-doc links are about to be stable](https://github.com/rust-lang/rust/pull/74430), I didn't make the effort to properly link various items in the documentation. This should fix itself soon, but I'm not sure with which release.

**Comment by jessebraham** [comment]
This feature seems to have landed in [1.48](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html), which released today.

**Comment by hannobraun** [comment]
Excellent! I'll leave this issue open until someone had a chance to look over the documentation. There are probably still some broken links, where the linked type is not in scope.
